setup.cfg, setup.py
Metadata has been updated with the current repository and authors' information.
=> Fix metadata in setup.py

deeprank_gnn/DataSet.py, deeprank_gnn/NeuralNet.py
The with clause will make the code easier to read.
If something goes wrong in the Dataset, the stacktrace will point out the Dataset, rather than throwing an exception elsewhere later on in execution.
A failsafe has also been added to prevent errors if no edge features are given.
=> Add a with clause to the Dataset.load_one_graph

README.md, deeprank_gnn/GraphGenMP.py, deeprank_gnn/preprocess.py, setup.py, tests/test_preprocess.py
Two changes to the way queries are preprocessed:
- use a python pool for multiprocessing
- do not use pickle to serialize feature modules, pass on the paths instead.
=> Fix the preprocessing

deeprank_gnn/NeuralNet.py, tests/test_nn.py
Run the neural network with transform_sigmoid set to true.
=> add a transform_sigmoid unit test

README.md, deeprank_gnn/DataSet.py, deeprank_gnn/NeuralNet.py, example/nn.py, tests/test_nn.py
When we use NeuralNet class, the first parameter is the path of the .hdf5 files, and this works well if we don't need to modify anything about them. Here I modify it so that you can pass the "customized" HDF5DataSet object to the NeuralNet class, according to the needs.
=> add hdf5dataset as input

deeprankcore/NeuralNet.py, deeprankcore/models/metrics.py, tests/test_nn.py
=> Check for metrics output compatibility with the output of a neural network model.

deeprankcore/DataSet.py, tests/test_dataset.py
It is tested that this new code doesn't result in any error, when ran.
=> adds the transform option to deeprank

README.md, setup.cfg
=> Install h5xplorer from pypi

deeprankcore/models/query.py
Hydrogens can contribute to electrostatic forces. However, adding them to structures can be time consuming.
This change makes it optional.
=> make hydrogen addition optional

deeprankcore/NeuralNet.py
This change allows the user to specify the filename to store the neural network model under.
=> makes the model path settable by the user

deeprankcore/DataSet.py, tests/test_nn.py
The dataset class will load the data from the hdf5 file to the cuda device. (if available) This should speed up the training process.
=> makes dataset use cuda for data tensors

deeprankcore/DataSet.py, deeprankcore/preprocess.py, tests/test_integration.py, tests/test_preprocess.py
This PR adds an integration test for the whole pipeline (data preprocessing - training a model - evaluation), see #95
=> Add integration test

deeprankcore/NeuralNet.py, tests/test_nn.py
=> add weight_decay to NeuralNet

deeprankcore/Metrics.py, deeprankcore/NeuralNet.py
remove threshold param from NeuralNet class and make it required in Metrics class
=> Remove rename params

deeprankcore/feature/__init__.py, tests/test_preprocess.py
- created generic function in test_preprocess.py instead of having 2 copies of same function
- in 2nd test: read all modules from deeprankcore.feature using importlib and test those
=> Auto test all features

deeprankcore/feature/atomic_contact.py
rewrote function to make it faster
=> Atomiccontact speed

deeprankcore/utils/grid.py, tests/utils/test_graph.py
This is tested in the test_graph test.
=> Makes sure that the `map_feature` function can handle single value features.

deeprankcore/trainer.py
=> refactor: update deprecated dataloader import

deeprankcore/trainer.py
=> fix: raise exception for invalid optimizer

deeprankcore/trainer.py
Fixes GPU runs which were failing due to tensors not being copied to the cpu for evaluation phase.
=> fix: gpu usage

deeprankcore/utils/graph.py, tests/utils/test_graph.py
The data is taken from the graph object and stored in the hdf5 file.
=> Make sure that Grid data also has target values, like graph data.

tests/features/test_contact.py
I made a few additions to your PR, I hope you don't mind.
Most of these clarify a bit better what is going on in each test, so it would have been very hard for you to do these, given that you are still very new to the package and don't what is actually being tested.
Take a look and see whether it makes sense to you, and ask away if anything is unclear.
BTW: I set this PR so that this will merge into your PR, not directly into main.
=> refactor: test_contact.py function naming and output

.github/actions/install-python-and-package/action.yml, README.md
Workflow with pytorch 2.0 and pyg dependencies from wheel (is faster than adding it to setup.cfg).
=> build: pytorch 2.0

README.md
=> docs: update dssp 4 install instructions

.github/actions/install-python-and-package/action.yml, README.md
The current PyPi release does not work with the documentation we have, because the release is outdated. I'll do a new release very soon but in the meantime we need to add that to the readme
=> docs: update README.md

deeprankcore/features/exposure.py
=> fix: cast `hse` feature to float64

deeprank2/dataset.py, deeprank2/features/secondary_structure.py, deeprank2/trainer.py
apparently there was still something wrong with the error message structure that was missed in the last PR and I only noticed just after merging the PR :(
=> docs: fix error message structure

env/requirements.txt
Somehow I forgot to update the Docker image's requirements with the last release.
=> bug: update requirements.txt
