README.md
Now coveralls points to the correct repo (deeprank-gnn-2), but to [fix-pytest branch](https://github.com/DeepRank/deeprank-gnn-2/tree/fix-pytest) (the only successful build is in this branch). We should change it with the main default branch, once issue #24 is solved.
=> Configure coveralls

.gitignore, deeprank_gnn/preprocess.py, tests/test_preprocess.py
Fixes #55 
This at least does an attempt to have something working on OSX, although we know that when using `.empty()` we already stop while some jobs are still running. This will be fixed with #56.
=> Use workaround for qsize not implemented on Mac OSX

deeprankcore/tools/graph.py, tests/data/pdb/3MRC/3MRC.pdb, tests/models/test_query.py
The method **build_residue_graph** has been adapted so that no more edges can be created between a residue and itself.
The query test now tests for this error.
=> Prevent a residue from being edged with itself

README.md, deeprankcore/DataSet.py, deeprankcore/NeuralNet.py, deeprankcore/Trainer.py, deeprankcore/models/query.py, docs/quickstart.md, docs/reference/deeprankcore.rst, example/nn.py, tests/test_dataset.py, tests/test_integration.py, tests/test_nn.py
Main edits
**General**
- Improved documentation in Trainer.py and DataSet.py
- Added `_` in front of methods meant to be only internal to the classes, so not supposed to be called by the user or somewhere outside the classes, in Trainer.py _and_ DataSet.py. 
**DataSet.py**
- Inserted a check for the target Dataset to be numerical since we do not support the categorical targets (for our experiments we have numerical target values so we don't care for now, but it's a nice addition for the future - see issue #197).
**NeuralNet.py (Trainer.py)**
- Modified NeuralNet class and module to Trainer
- Moved `_PreCluster` and `_DivideDataSet` functions to Trainer.py module since they are used only in there. I put `_PreCluster` as `Trainer` method and I left `_DivideDataSet` as a function for now. In …
=> NeuralNet class alignment to high-level frameworks

.github/actions/install-python-and-package/action.yml
build is failing with newest pytorch (1.13), but should work with this pytorch version (1.12.1).
let's check again in some time if pytorch 1.13 also works
=> build with pytorch 1.12.1

.github/actions/install-python-and-package/action.yml, deeprankcore/query.py, setup.cfg
The process method of Query was failing if the script was run outside the package, due to the way in which we listed features modules' names. Using `pkgutil` solves the issue.
=> fix: list all submodules imported from deeprankcore.features using pkgutil

deeprankcore/query.py
If a graph build fails, now the error is caught and printed in the log, together with the id of the query failed.
=> perf: add try except clause to `_preprocess_one_query` method of `QueryCollection` class

README.md, deeprankcore/dataset.py, deeprankcore/trainer.py
- `classes` argument of GraphDataset now can be also made of strings
- If it's None, it's defaulted to [0, 1] and this is printed in the logging file
- Add in the readme useful info for developers
=> fix: let `classes` argument be also categorical

deeprankcore/dataset.py, deeprankcore/trainer.py, tests/test_dataset.py, tests/test_trainer.py
- Move `transform_sigmoid` parameter, now called `target_transform`, to GraphDataset class
- Only the target (ground truth) is now transformed with a log and a sigmoid function. The prediction will be done according to such a transformed target. 
- An error is raised if the user tries to set`target_transform` as True but the task is not regression
- Tests and docs have been added accordingly
=> refactor: fix `transform_sigmoid` logic and move it to `GraphDataset` class

deeprankcore/dataset.py, deeprankcore/trainer.py, tests/test_trainer.py
- Improve docs about the clustering operations and their usage
- Default `clustering_method ` of `GraphDataset` to None, since clustering is specific for only some networks and shouldn't be done by default
=> docs: improve `clustering_method` description and default value

deeprankcore/dataset.py, deeprankcore/trainer.py, tests/test_trainer.py
This PR:
- Fixes `num_workers` parameter usage of Dataloader, which allows to load data in parallel on multiple CPUs. Data are initially loaded to CPUs only, to allow such parallelization and to let the user use `num_workers`.
- Improves the handling of the cuda device, transferring data to GPU only during training (tested and working on Snellius).
- Makes facultative doing the checks on the hdf5 files that can take long times in case of bigger datasets, and do not need to be repeated in each experiment.
- Defaults the clustering method to None (again, don't know why it was defaulted to mcl again).
=> fix: `num_workers` parameter of Dataloader object

.gitignore, tests/test_integration.py, tests/test_set_lossfunction.py, tests/test_trainer.py
The models created in some of the unit tests were stored inside the repo in a few different places.
Also, the assertion to check for output_exporter in test_trainer was recognizing output from previous unit tests. These are now cleared at the beginning of each test.
=> refactor: delete all outputs from unit tests after run

deeprankcore/molstruct/residue.py, deeprankcore/query.py, deeprankcore/utils/graph.py, deeprankcore/utils/grid.py, tests/test_integration.py, tests/utils/test_graph.py, tests/utils/test_grid.py
Grids must be given a center position on creation.
With this modification, the query object assigns a center position to the graph objects. For single residue variant graphs, this is the variant residue position. For protein-protein interaction graphs, this is the mean of the contacting atom positions.
When the graph is converted into a grid, this center position is passed on and it will determine the position of the grid points.
A test has been added to check that the center position is the same as in the original deeprank.
=> feat: center the grids as in the old deeprank

.github/workflows/stale_issue_pr.yml
I think we actually want old issues to just stay open, right? Until now, we were constantly removing the stale label. 
I think better to just leave as stale forever, so it's still clear that this is an "old" issue, but not close it until it's done. This way we can occasionally check the stale issues and see whether they have been done in the meantime or whether it is time to pick one up.
=> ci: do not close stale issues or PRs

deeprankcore/dataset.py
In `DeeprankDataset` class, `Optional[Union[...]]` was used as a type hint in a few cases, where only one possibility existed (apart from the `None` of Optional).
This was probably a remnant of the previous formulation of `Union[..., None]`. However, because now `Optional` is used, `Union` should not be anymore.
=> docs: incorrect usage of Union in Optional type hints

deeprankcore/domain/edgestorage.py, deeprankcore/features/contact.py, tests/data/hdf5/_generate_testdata.ipynb, tests/features/test_contact.py, tests/test_dataset.py, tests/test_query.py, tests/test_trainer.py
Prior to this PR, nodes on separate chains could be considered to be covalent pairs (for "covalent" feature) and 1-3 or 1-4 pairs (for energy features), as these were all based solely on cutoff distances.
Now, the code also checks whether nodes are on the same chain or not, and only considers them bonded if they are on the same chain.
closes #407
=> fix: covalent bonds cannot link nodes on separate branches

deeprankcore/query.py, tests/utils/test_graph.py
Originally we were testing everything in only one test; now I divided the tests into three more logical ones, and I added few more asserts to improve coverage.
=> test: improve `utils/test_graph.py` module

deeprankcore/query.py, tests/test_query.py
- Only run `_check_pssms` if conservation module is active
- Test that runs without error if module is not used, even if pssms are bad
- Make error less verbose
- Add test for error if missing or typoed/incorrect pssm filenames
Error is still raised and hdf5 files not created if pssm files are faulty, as per [this comment](https://github.com/DeepRank/deeprank-core/issues/424#issuecomment-1548080457).
closes #424
=> fix: only check pssms if conservation module was used

README.md, deeprankcore/trainer.py, docs/getstarted.md, tests/test_integration.py, tests/test_set_lossfunction.py, tests/test_trainer.py
Main changes proposed with this PR:
- `train` method has two distinct parameters now for indicating if the user wants to save either the best or the last model, and if the model needs to be saved. This way it's easier to do internal checks, and it's clearer for the user. 
- `save_model` method it's internal now and it saves only the state dict by default, into a variable which is then used in the code
- The state dict needs to be retained to load the states of the best/last model at the end of the training loop
- After the training loop is over, the best/last model state is saved in a file if the new flag `save_model` is True
- Before these edits, we were overriding the file every time we were saving the best model. Also, we were not loading the state dicts of the best model to the …
=> fix: epoch number in `test()` and test on the correct model

deeprankcore/dataset.py
The following code in `GridDataset` (deeprankcore/dataset.py:549) `data = Data(x=torch.tensor([feature_data], dtype=torch.float)`, in which feature_data was a list of numpy arrays, gave this warning:
```bash
UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1670525539683/work/torch/csrc/utils/tensor_new.cpp:230.)
```
Now it is fixed by using numpy arrays instead of list object.
This PR solves the first part of #308
=> fix: convert list of arrays into arrays before converting to Pytorch tensor

tests/utils/test_graph.py
This function doesn't always output the same result and rarely it had exceeded the 0.11 on my system and the test fails (but then passes if I rerun it). Can I increase it to 0.2 or could that be a problematic value?
=> CI: decrease sensitivity of `test_graph_augmented_write_as_grid_to_hdf5`

deeprankcore/dataset.py
After the edits merged with PR #446, the code was throwing warnings any time an instance of GraphDataset/GridDataset with `train=False`, `dataset_train=dataset_train` (the correct one), and with default task, target, features, ... parameters was defined. 
More in detail, the internal function `_check_inherited_params` (dataset.py module) was throwing a warning any time the attributes of the validation/test sets were different from the ones of the training dataset, which can be true if the validation/test sets' attributes themselves are not set by the user, who just passes in the training set (assuming inheritance).
- Now the warning is thrown only if the user sets a validation/test sets parameter different from the default and different from the training set one. 
- Also, `features_dict` …
=> fix: `dataset_train` inheritance warnings

.bumpversion.cfg, .readthedocs.yaml, deeprank2/features/contact.py, deeprank2/trainer.py, docs/conf.py, docs/index.rst, docs/installation.md, docs/requirements.txt, setup.cfg, tutorials/training_ppi.ipynb
This PR fixes readthedocs documentation for the newly named deeprank2 package. In particular:
- as mentioned [here](https://blog.readthedocs.com/migrate-configuration-v2/), readthedocs builds without a configuration file are now deprecated. I added a .readthedocs.yml file to address it. The specific dependencies needed are now specified in docs/requirements.txt, as indicated in the newly added .yml file.
- I updated a .md parser dependency to `myst-parser` as indicated [here](https://github.com/readthedocs/recommonmark), since `recommonmark` won't be maintained anymore and is now deprecated.
- I removed `setuptools.config.read_configuration` from docs/conf.py since it's now deprecated. We're now using `configparser.ConfigParser()`. 
- I fixed the remaining old namings using the new …
=> fix: readthedocs after deeprank2 renaming

deeprank2/tools/visualization/plotting.py, deeprank2/utils/community_pooling.py, setup.cfg
This error is described in #477. Converting the sparse array to a dense array type stops the error from appearing.
=> fix: make scipy 1.11.2 work

README.md, docs/installation.md
Feel free to merge it right away if you have no comments about this PR
- ask to check whether dssp is already installed before saying to install (it's sudo installed, so only needs to be done once).
- give full command in the example of the "Dependencies for pytorch geometric from wheels" part
=> docs: minor improvements to install instructions

deeprank2/trainer.py, tests/test_integration.py
During the training (in the `trainer.Trainer.train() method`), if the loss is nan (such as when using very few datapoints, like in #528), `checkpoint_model` is never created, thus the crashes and gives the following error:
```bash
UnboundLocalError: local variable 'checkpoint_model' referenced before assignment
```
This PR adds checks for handling such cases and integration tests. 
- I used [tmpdir_factory](https://docs.pytest.org/en/6.2.x/tmpdir.html#the-tmpdir-factory-fixture) fixture for generating the hdf5 files needed for the checks only once per tests' session.
- I used [pytest.mark.parametrize](https://docs.pytest.org/en/7.3.x/how-to/parametrize.html#how-to-parametrize-fixtures-and-test-functions) for passing in multiple inputs to the test function.
=> fix: handle cases in which losses are nan during the training

deeprank2/trainer.py, tests/test_trainer.py
- The bug was due to the quotation marks type used in the regex for extracting the transform function. The quotation marks are indeed now automatically fixed to double type by ruff in our VSCode editor. Since a user should be able to use both types of quotation marks, I changed the regex that matches the `transform` function for handling both cases. The bug was causing the failure of the `training.ipynb` notebook.
- I also added a test for checking on the `features_transform` attribute in the `Trainer`, and in case we use a pre-trained model. The testing on the trainer side for features_transform was missing. 
As soon as this is approved, I will release a new patch version for deeprank2.
=> fix: features transform in `Trainer._save_model` internal method

.github/workflows/linting.yml, .vscode/settings.json, CONTRIBUTING.rst, README.dev.md, deeprank2/trainer.py, deeprank2/utils/community_pooling.py, env/deeprank2-docker.yml, env/deeprank2.yml, pyproject.toml, tests/domain/test_forcefield.py, tests/features/__init__.py, tests/features/test_contact.py, tests/molstruct/test_structure.py, tests/perf/ppi_perf.py, tests/perf/srv_perf.py, tests/test_dataset.py, tests/test_querycollection.py, tests/utils/test_buildgraph.py, tests/utils/test_graph.py, tests/utils/test_pssmdata.py
I updated the ruff version and made some minor style improvements throughout the code.
=> style: update ruff

MANIFEST.in, NOTICE, pyproject.toml
The PyPI release 3.0.2 still contains the tests folder. Using a MANIFEST.in where we prune (exclude) the tests should fix the issue. We will verify this in the next release (not a major issue). Also, I created a NOTICE file for the copyright, that was missing.
=> docs: improve handling pypi packaging contents and add NOTICE

deeprank2/trainer.py, deeprank2/utils/grid.py, docs/conf.py, env/deeprank2-docker.yml, env/deeprank2.yml, pyproject.toml
While training a big network I got: `OSError: could not get source code` from the `_save_model()` method of the `Trainer` class, in particular when we do `str_expr = inspect.getsource(key["transform"])`. The error indicates that the inspect module is unable to retrieve the source code for the lambda function stored in `key["transform"]`.
- I fixed it by using `dill` to serialize and deserialize the functions, which appears to be more reliable.
- I changed the `scipy.signal.bspline` import to `scipy.interpolate.BSpline` to be up to date with a more recent version of scipy (minimum 1.13.1) as indicated in one of their latest releases ([1.13.0](https://github.com/scipy/scipy/releases/tag/v1.13.0)). I did this since we prefer to not fix the versions, but just to indicate the minimum, and the …
=> fix: OSError when retrieving source code for lambda functions

.github/workflows/linting.yml
Linting doesn't require the entire package to be built, merely ruff to be installed.
Note that the lint action only takes 7 sec now, compared to e.g. 5 min in #611
=> ci: simplify lint action

deeprank2/tools/target.py, deeprank2/trainer.py, deeprank2/utils/parsing/residue.py, pyproject.toml, tests/test_integration.py, tests/test_querycollection.py
I did a few test asserts to ensure that the dicts here are identical to the dicts as they were previously formatted
=> ci: update ruff and fix linting rules

deeprank2/neuralnets/cnn/model3d.py, deeprank2/neuralnets/gnn/foutnet.py, deeprank2/neuralnets/gnn/ginet.py, deeprank2/neuralnets/gnn/ginet_nocluster.py, deeprank2/neuralnets/gnn/naive_gnn.py, deeprank2/neuralnets/gnn/sgat.py, deeprank2/trainer.py, tests/test_trainer.py
- All functions from torch.nn.functional are now explicitly imported by name and used directly.
- In all other cases where classes from torch.nn are used, we do `from torch import nn` and then use `nn.<Class>` throughout.
Note that this was also changed in one docstring in fba9e56. Not sure if that messes up the rendering of the documents. That commit can easily be dropped if needed.
fix #269
=> style: make torch.nn imports more uniform

Dockerfile
While investigating issue #540, I encountered a problem with our Dockerfile build process. The root cause was a version mismatch with `libstdc++.so.6`, leading to the following error during a SciPy import:
```bash
libstdc++.so.6: version `GLIBCXX_3.4.29' not found
```
- The error occurred because the container was incorrectly linking to an outdated version of `libstdc++.so.6` from the system's root directory, rather than the newer version available in the Conda environment.
- Although the required GLIBCXX_3.4.29 symbol was present in the Conda-managed version of `libstdc++.so.6`, the container failed to detect it and instead used the system's older version.
To resolve this, I made the following changes:
- Updated the base image: I changed the base image from `ubuntu:20.04` to …
=> fix: dockerfile image build
